version: '2'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/main
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=team_andrew
      - MONGO_INITDB_ROOT_PASSWORD=Green
  
