version: '2'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/app
  app2:
    build:
      context: .
      dockerfile: app2.dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app2
  
